import type { Metadata } from 'next'
import './globals.css'
import { ABeeZee } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';


const inter = ABeeZee({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* 會把東西拔出去變成component */}
        {/* <div className='absolute w-full z-10'>
          <div className='flex justify-between container mx-auto text-white p-8'>
            <Link className='text-3x-l font-bold' href='/'>
              {' '}
              Home
            </Link>
            <div className='text-x1 space-x-4'>
              <Link href='/performance'>Performance</Link>
              <Link href='/reliability'>Reliability</Link>
              <Link href='/scale'>Scale</Link>
            </div>
          </div>
        </div> */}

        {/* 會發現在404 header 也會出現，因為404也是children，所以要經由usePathname 區隔要出現位置的url才顯現，不然返回空，並請只能回去那個componet 設計（ex:header） */}

        {/* 移到router group 了 */}
        {/* <Header/> */}
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  )
}
